#' @title Filter columns of a server-side object based on a missingness threshold
#'
#' @description Computes the percentage of missing values for each variable in a distributed
#' data set and optionally removes variables exceeding a user-defined threshold.
#'
#' The function supports two filtering strategies:
#' \itemize{
#'   \item \code{"combined"}: computes a global missingness percentage for each
#'   variable as a weighted average across all servers. The same set of variables
#'   is removed from all servers.
#'   \item \code{"split"}: evaluates missingness independently on each server and
#'   removes server-specific sets of variables.
#' }
#'
#' A missingness table is always displayed. When variables exceed the threshold,
#' they are reported along with their missingness percentages.
#'
#' If no variables exceed the threshold, no filtering is applied and the original
#' data remain unchanged.
#'
#' Server-side functions called: \code{check_missing_dataDS}, \code{remove_columnsDS}
#'
#' @param df A character string specifying the name of the input data frame
#' stored on each server.
#' @param threshold A numeric value between 0 and 100 representing the maximum
#' allowed percentage of missing values per variable.
#' @param type A character string specifying the filtering strategy:
#' \code{"combined"} (default) or \code{"split"}.
#' @param remove A logical value indicating whether flagged variables should be
#' removed. If \code{TRUE} (default), filtered data are stored server-side using
#' \code{remove_columnsDS}. If \code{FALSE}, variables exceeding the threshold are
#' only identified and returned, without modifying any server-side object.
#' @param preproc_newobj A character string specifying the name of the output
#' server-side object. If \code{NULL}, a name is automatically generated by
#' appending \code{"_preprocessed"} to \code{df}. Ignored if \code{remove = FALSE}.
#' @param datasources A list of \code{\link[DSI]{DSConnection-class}} objects.
#' If not provided, the default active connections are used.
#'
#' @return
#' \itemize{
#'   \item If \code{remove = TRUE}: invisibly returns a character string with the
#'   name of the created server-side object containing the filtered data. If no
#'   variables exceed the threshold, the original data are left unchanged and the
#'   intended output object name is still returned.
#'   \item If \code{remove = FALSE}:
#'   \itemize{
#'     \item For \code{type = "combined"}: a character vector of variables exceeding
#'     the threshold.
#'     \item For \code{type = "split"}: a named list of character vectors (one per
#'     server) containing variables exceeding the threshold.
#'     \item \code{NULL} if no variables exceed the threshold.
#'   }
#' }
#'
#' @export

ds.check_missing_data <- function(df,
                                  threshold,
                                  type = c("combined", "split"),
                                  remove = c(TRUE, FALSE),
                                  preproc_newobj = NULL,
                                  datasources = NULL) {
  if (is.null(datasources))
    datasources <- datashield.connections_find()
  if (is.null(preproc_newobj))
    preproc_newobj <- paste0(df, "_preprocessed")

  type   <- match.arg(type)
  remove <- isTRUE(remove[1])

  # Compute % missing per server
  miss_list <- DSI::datashield.aggregate(
    conns = datasources,
    expr  = call("check_missing_dataDS", as.symbol(df))
  )
  ref_cols <- names(miss_list[[1]])
  for (x in miss_list) {
    if (!identical(names(x), ref_cols))
      stop("Not all servers have the same columns.")
  }
  miss_tab <- as.data.frame(miss_list)
  colnames(miss_tab) <- names(datasources)

  # ── TYPE == COMBINED ──────────────────────────────────────────────────────
  if (type == "combined") {
    dims    <- dsBaseClient::ds.dim(df, type = "split", datasources = datasources)
    n_vec   <- sapply(dims, function(x) x[1])
    names(n_vec) <- names(dims)
    miss_mat <- sapply(miss_tab[, names(datasources)], as.numeric)
    miss_tab$global <- (miss_mat %*% n_vec) / sum(n_vec)

    vars_to_remove <- rownames(miss_tab)[miss_tab$global > threshold]

    message("\n Missingness Table (%)")
    tbl_txt <- capture.output(round(miss_tab, 2))
    message(paste(tbl_txt, collapse = "\n"))
    message("\n Variables flagged (Global Missing > ", threshold, "%)")

    if (length(vars_to_remove) == 0) {
      message("None")
      message("\nNo columns need to be removed")
      if (remove) {
        message("\n Preprocessed data stored as: ", preproc_newobj)
        return(invisible(preproc_newobj))
      }
      return(invisible(NULL))
    }

    removed_tab <- data.frame(
      variable       = vars_to_remove,
      global_missing = round(miss_tab[vars_to_remove, "global"], 2),
      row.names      = NULL
    )
    tbl_txt <- capture.output(removed_tab)
    message(paste(tbl_txt, collapse = "\n"))

    if (!remove) {
      message("\n remove = FALSE: no columns are removed.")
      return(invisible(vars_to_remove))
    }

    # remove = TRUE
    cols_string <- if (length(vars_to_remove) == 1) {
      paste0(vars_to_remove, "$")
    } else {
      paste(vars_to_remove, collapse = "$")
    }
    DSI::datashield.assign.expr(
      conns  = datasources,
      symbol = preproc_newobj,
      expr   = call("remove_columnsDS", as.symbol(df), cols_string)
    )
  }

  # ── TYPE == SPLIT ─────────────────────────────────────────────────────────
  if (type == "split") {
    message("\n Missingness Table (%)")
    tbl_txt <- capture.output(round(miss_tab, 2))
    message(paste(tbl_txt, collapse = "\n"))

    vars_to_remove_list <- lapply(colnames(miss_tab), function(srv) {
      rownames(miss_tab)[miss_tab[[srv]] > threshold]
    })
    names(vars_to_remove_list) <- colnames(miss_tab)

    message("\n Variables flagged per Server (Missing > ", threshold, "%)")
    for (srv in names(vars_to_remove_list)) {
      message("\n ", srv, ":")
      vars_srv <- vars_to_remove_list[[srv]]
      if (length(vars_srv) == 0) {
        message("None")
      } else {
        removed_tab <- data.frame(
          variable    = vars_srv,
          missing_pct = round(miss_tab[vars_srv, srv], 2),
          row.names   = NULL
        )
        tbl_txt <- capture.output(removed_tab)
        message(paste(tbl_txt, collapse = "\n"))
      }
    }

    tot_removed <- sum(lengths(vars_to_remove_list))

    if (tot_removed == 0) {
      message("\nNo columns need to be removed")
      if (remove) {
        message("\n Preprocessed data stored as: ", preproc_newobj)
        return(invisible(preproc_newobj))
      }
      return(invisible(NULL))
    }

    if (!remove) {
      message("\n remove = FALSE: no columns are removed.")
      return(invisible(vars_to_remove_list))
    }

    # remove = TRUE: call remove_columnsDS per server
    for (srv in names(datasources)) {
      vars_srv <- vars_to_remove_list[[srv]]
      if (length(vars_srv) == 0)
        next
      cols_string <- if (length(vars_srv) == 1) {
        paste0(vars_srv, "$")
      } else {
        paste(vars_srv, collapse = "$")
      }
      DSI::datashield.assign.expr(
        conns  = datasources[srv],
        symbol = preproc_newobj,
        expr   = call("remove_columnsDS", as.symbol(df), cols_string)
      )
    }
  }

  message("\n Preprocessed data stored as: ", preproc_newobj)
  invisible(preproc_newobj)
}





